### ISSUE TITLE
No station found

### ISSUE THREAD

**Issue by aminmuo** [adrianmo/pymeteoclimatic#7]
Hello, I am trying to access a station with the Meteoclimatic seal, but when I try to access it, I get the message: "No devices found on the network." With other stations, I am able to get the data.

The station is: ESPVA4600000046340A

Can you tell me what the issue might be?

Thank you!

**Comment by adrianmo** [comment]
@aminmuo it's really strange. I've checked that the [website profile](https://www.meteoclimatic.net/perfil/ESPVA4600000046340A) works fine, but then the RSS feed, which is where we get the data from in this library, does not return any data.

You can try yourself. Run `curl https://www.meteoclimatic.net/feed/rss/ESPVA4600000046340A` and you will get no station data. Then use any other station code like `curl https://www.meteoclimatic.net/feed/rss/ESPVA4600000046260B` and you'll see the data as expected.

You should probably reach out to the Meteoclimatic team directly or post a message in the [forum](https://forum.meteoclimatic.net/) so that somebody in Meteoclimatic can investigate the issue internally.

Please reply here when you figure something out. I'll close this issue for now as this doesn't seem to be related with the library. If based on the Meteoclimatic response, we need to make any adjustment to the library, we will reopen it.

Thank you!

**Comment by aminmuo** [comment]
I just checked, and it looks like the station’s been offline for a few hours, right around the time I tried to get the data—a coincidence, since the station has the Meteoclimatic seal. The outage might’ve been caused by the rough weather in the area.

Thanks a lot, @adrianmo. Sorry about the question but I really don't know the reason of the issue.
